using System.CommandLine;
using System.CommandLine.IO;
using System.IO.Abstractions.TestingHelpers;
using System.Threading.Tasks;
using FluentAssertions;
using VerifyXunit;
using Xunit;
using static VerifyXunit.Verifier;

namespace ResponsibleGherkin.Tests;

[UsesVerify]
public class ProgramTests
{
	private readonly MockFileSystem fileSystem = new();
	private readonly TestConsole console = new();

	public ProgramTests()
	{
		this.fileSystem.AddFile(
			"config.json",
			new MockFileData(TestFeatures.DefaultConfigurationJson));

		this.fileSystem.AddFile(
			"MinimalFeature.feature",
			TestFeatures.MinimalFeatureString);

		this.fileSystem.AddFile(
			"UnsupportedKeyword.feature",
			TestFeatures.UnsupportedKeywordFeatureString);

		this.fileSystem.AddFile(
			"InvalidFeature.feature",
			new MockFileData("foobar"));
	}

	[Fact]
	public async Task Verify_Output_WhenNoArguments()
	{
		this.RunAssertingFailure();
		await Verify(this.ConsoleOutput());
	}

	[Theory]
	[InlineData("configure")]
	[InlineData("generate")]
	public async Task Verify_CommandHelp(string command)
	{
		this.RunAssertingSuccess(command, "-h");
		await Verify(this.ConsoleOutput()).UseParameters(command);
	}

	[Fact]
	public async Task Verify_SuccessfulConfigure()
	{
		this.RunAssertingSuccess("configure", "xunit", "MyNamespace", "BddTest", "Executor", "tabs", "1");
		await Verify(this.ConsoleOutput());
	}

	[Fact]
	public void Generate_ProducesSameResultAsManualInvoke()
	{
		var expected = CodeGenerator.GenerateClass(
				TestFeatures.LoadFeature("MinimalFeature").Feature,
				TestFeatures.DefaultConfiguration)
			.BuildFileContent();

		this.RunAssertingSuccess("generate", "config.json", "MinimalFeature.feature", "./");
		var generatedContent = this.fileSystem.File.ReadAllText("MinimalFeature.cs");

		generatedContent.Should().Be(
			expected,
			"it should match code generated by invoking CodeGenerator directly");
	}

	[Fact]
	public void Generate_ContainsDescriptiveError_WhenConfigFileIsMissing()
	{
		this.RunAssertingFailure("generate", "foobar", "MinimalFeature.feature", "./");
		this.ConsoleErrors().Should().Contain("read configuration");
	}

	[Fact]
	public void Generate_ContainsDescriptiveError_WhenInputFileIsMissing()
	{
		this.RunAssertingFailure("generate", "config.json", "foobar", "./");
		this.ConsoleErrors().Should().Contain("read input");
	}

	[Fact]
	public void Generate_ContainsDescriptiveError_WhenInputFileIsInvalid()
	{
		this.RunAssertingFailure("generate", "config.json", "InvalidFeature.feature", "./");
		this.ConsoleErrors().Should().Contain("read input");
	}

	[Fact]
	public void Generate_ContainsDescriptiveError_WhenInputFileIsNotSupported()
	{
		this.RunAssertingFailure("generate", "config.json", "UnsupportedKeyword.feature", "./");
		this.ConsoleErrors().Should().Contain("generate code");
	}

	[Fact]
	public void Generate_ContainsDescriptiveError_WhenDirectoryIsInvalid()
	{
		this.RunAssertingFailure("generate", "config.json", "MinimalFeature.feature", "*");
		this.ConsoleErrors().Should().Contain("write output");
	}

	[Fact]
	public void Generate_CreatesOutputDirectory_WhenItDoesNotExist()
	{
		this.RunAssertingSuccess("generate", "config.json", "MinimalFeature.feature", "./Output");
		this.fileSystem.Directory.Exists("Output").Should().BeTrue("it should be created");
		this.fileSystem.File.Exists("Output/MinimalFeature.cs").Should().BeTrue("the file should be generated");
	}

	private void RunAssertingFailure(params string[] args)
	{
		this.Run(args).Should().NotBe(0, $"the run should fail, output was {this.console.Out}");
	}

	private void RunAssertingSuccess(params string[] args)
	{
		this.Run(args).Should().Be(0, $"Run should succeed, failed with {this.console.Error}");
	}

	private int Run(params string[] args) => Program
		.BuildRootCommand(this.fileSystem)
		.Invoke(args, this.console);

	private object ConsoleOutput() => new
	{
		Out = this.console.Out.ToString(),
		Error = this.ConsoleErrors(),
	};

	private string? ConsoleErrors() => this.console.Error.ToString();
}
