name: "Check changelog"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dangoslen/changelog-enforcer@v2
      with:
        missingUpdateErrorMessage: "Please update CHANGELOG.md or add the Skip-Changelog label if not needed!"
