name: Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-unity:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.14f1
          - 2020.3.1f1

        # No dots allowed in secret names, so we need to have this mapping
        include:
          - unityVersion: 2019.4.14f1
            licenseSecret: UNITY_LICENSE_2019
          - unityVersion: 2020.3.1f1
            licenseSecret: UNITY_LICENSE_2020

    steps:
      - uses: actions/checkout@v3

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}

      - name: Cache
        uses: actions/cache@v3.0.1
        with:
          path: ResponsibleUnity/Library
          key: Library-${{ matrix.unityVersion }}-${{ hashFiles('com.beatwaves.responsible/**', 'ResponsibleUnity/**') }}
          restore-keys: |
            Library-${{ matrix.unityVersion }}
            Library-

      - name: Run tests
        id: tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets[matrix.licenseSecret] }}
        with:
          projectPath: ResponsibleUnity
          unityVersion: ${{ matrix.unityVersion }}
          customParameters: -enableCodeCoverage
            -coverageResultsPath "../artifacts/CodeCoverage/"
            -coverageOptions assemblyFilters:+Responsible,+Responsible.Editor
            -debugCodeOptimization
            -nographics
            -disable-assembly-updater

      - name: Push to testspace
        if: ${{ always() }}
        run: testspace
          [${{ matrix.unityVersion }}]artifacts/editmode-results.xml
          [${{ matrix.unityVersion }}]artifacts/playmode-results.xml

      - name: Push to codecov.io
        if: ${{ always() }}
        uses: codecov/codecov-action@v3
        with:
          flags: Unity${{ matrix.unityVersion }}
          files: "artifacts/CodeCoverage/ResponsibleUnity-opencov/EditMode/TestCoverageResults_0000.xml,\
            artifacts/CodeCoverage/ResponsibleUnity-opencov/PlayMode/TestCoverageResults_0000.xml"
          fail_ci_if_error: true

      - name: Archive test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Unity Test Results ${{ matrix.unityVersion }}
          path: artifacts

  test-netstandard:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Responsible

    strategy:
          fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}

      - name: Run Tests
        id: run-tests
        run: |
          dotnet test --collect:"XPlat Code Coverage" -r TestResults --settings runsettings.xml --logger "trx;LogFileName=results.xml"
          echo "::set-output name=coverage::Responsible/$(ls TestResults/*/* | head -n1)"
          echo "::set-output name=tests::TestResults/results.xml"

      - name: Push to testspace
        if: ${{ always() }}
        run: testspace ${{ steps.run-tests.outputs.tests }}

      - name: Push to codecov.io
        uses: codecov/codecov-action@v3
        if: ${{ always() }}
        with:
          flags: netstandard
          files: ${{ steps.run-tests.outputs.coverage }}
          fail_ci_if_error: true

      - name: Archive test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: netstandard Test Results
          path: Responsible/TestResults

  test-mutation:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Responsible

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - name: dotnet restore
        run: |
          dotnet restore
          dotnet tool restore

      - name: Set version to PR number
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo "STRYKER_VERSION=${{ github.event.number }}" >> $GITHUB_ENV

      - name: Set version to main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "STRYKER_VERSION=main" >> $GITHUB_ENV

      - name: Run Stryker Mutation Testings
        run: dotnet stryker --reporter dashboard --dashboard-api-key ${{ secrets.STRYKER_KEY }} --version ${{ env.STRYKER_VERSION }}

  inspectcode:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Responsible

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - name: dotnet restore
        run: |
          dotnet restore
          dotnet tool restore

      - name: Run ReSharper
        run: ./inspectcode.sh

      - name: Archive ReSharper run
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ReSharper
          path: Responsible/inspect.xml

      - name: ReSharper XML -> GitHub output
        if: ${{ always() }}
        uses: glassechidna/resharper-action@v1
        with:
          report: Responsible/inspect.xml
