on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
    secrets:
      STRYKER_KEY:
        required: true

jobs:
  stryker:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6'

      - name: dotnet restore
        run: |
          dotnet restore
          dotnet tool restore

      - name: Set version to PR number
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo "STRYKER_VERSION=${{ github.event.number }}" >> $GITHUB_ENV

      - name: Set version to main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "STRYKER_VERSION=main" >> $GITHUB_ENV

      - name: Run Stryker Mutation Testings
        run: dotnet stryker --reporter dashboard --dashboard-api-key ${{ secrets.STRYKER_KEY }} --version ${{ env.STRYKER_VERSION }}
